// export const GET_RESPONSE_REQUEST = "NEWTON::GET_RESPONSE_REQUEST";
export const GET_RESPONSE_SUCCESS = "NEWTON::GET_RESPONSE_SUCCESS";
export const GET_RESPONSE_FAILURE = "NEWTON::GET_RESPONSE_FAILURE";
